# Display a box
print("type a letter do display beep\'s eye")
eye = input()
print("##########")
print("# ", eye, "",eye, " #")
print("#  \__/  #")
print("##########")
print("    ##    ")
print("##########")
print("# ###### #")
print("# ###### #")
print("# ###### #")
print("  ######  ")
print("  ##  ##  ")
print("  ##  ##  ")
print("  ##  ##  ")
print(" ###  ### ")